services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: favoriten-backend
    command: gunicorn -w 2 -b 0.0.0.0:5000 app:app
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - favoriten-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: favoriten-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - favoriten-network

networks:
  favoriten-network:
    driver: bridge