version: '3.8'

services:
  # Backend (Python Flask)
  backend:
    build: ./backend
    container_name: favoriten-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - FLASK_ENV=production
    volumes:
      - backend-data:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - favoriten-network

  # Frontend (Nginx + HTML/CSS/JS)
  frontend:
    build: ./frontend
    container_name: favoriten-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - favoriten-network

volumes:
  backend-data:
    driver: local

networks:
  favoriten-network:
    driver: bridge